# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-15 22:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_auto_20170215_2226'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pizza_Toppings',
            new_name='Pizza_Topping',
        ),
    ]
